### ISSUE TITLE
项目结构规划及部分工具代码实现

### ISSUE THREAD

**Issue by DengBoCong** [hlp-ai/hlp#1]
+ 完成基本的项目结构规划
   + 考虑方便除GPT-2及seq2seq实现外的其他多模型加入
   + 考虑工具代码复用
   + 考虑模型构成后实际体验Web效果，Web结构，可视化切换等
   + ......
+ 部分工具代码实现
   + 完成Encoder相关思路实现
   + 完成Attention相关思路实现
   + 完成Decoder相关思路实现
   + 组合成一个基本的seq2seq模型的对话系统结构
   + ......

**Comment by hlp-ai** [comment]
作为Issue有点大，可以放到milestone中补充。Issue最好2天左右可以实现。

**Comment by hlp-ai** [comment]
后面记得把有关Issue信息：如Assignee等补充一下，便于查看和查询。

**Comment by hlp-ai** [comment]
Web界面使用可以暂不考虑。
命令行使用优先。
提供web服务接口倒是未来可以考虑的地方。

**Comment by hlp-ai** [comment]
对各种对话数据集的一致方便访问很重要。（需要抽象和设计）
这也许是后面开发最重要的可复用的地方之一。

**Comment by DengBoCong** [comment]
好的，Assignee貌似只能由owner设置。
我稍后重提一个这两天的工作。

**Comment by DengBoCong** [comment]
数据集的管理我到时候想想怎么做合适，我正好整理了一下之前接触到的对话数据集

**Comment by hlp-ai** [comment]
变与不变：数据集可变，访问接口可以不变；训练、测试功能不变，模型或配置可变；
