### ISSUE TITLE
初始化项目结构，完成Seq2Seq的base

### ISSUE THREAD

**Issue by DengBoCong** [hlp-ai/hlp#2]
初始化项目结构，完成Seq2Seq的base

**Comment by hlp-ai** [comment]
#7 有以下几个问题：
1. 在chat下再建子目录，如seq2seq，表示基于seq2seq的闲聊系统实现；
2. 去掉和本次功能提交无关或暂时无关的目录和文件。

**Comment by DengBoCong** [comment]
我开始的想法是在model文件夹下建的seq2seq、GPT-2等主要代码，其他如config，common放通用抽血的代码

**Comment by hlp-ai** [comment]
> 我开始的想法是在model文件夹下建的seq2seq、GPT-2等主要代码，其他如config，common放通用抽取的代码

这个想法可以。通用的可以放到chat目录下。

**Comment by hlp-ai** [comment]
> #7 有以下几个问题：
> 
> 1. 在chat下再建子目录，如seq2seq，表示基于seq2seq的闲聊系统实现；
> 2. 去掉和本次功能提交无关或暂时无关的目录和文件【只提交必要和相关的内容】。

3. 包和模块的导入有问题，既不是相对导入，也不是绝对导入。应该使用相对导入。

**Comment by hlp-ai** [comment]
为了容易验证程序功能，可以放需要的玩具数据。

**Comment by hlp-ai** [comment]
D:\anaconda3\envs\tensorflow2\python.exe D:/hlp/github/hlp/hlp/chat/execute.py
Traceback (most recent call last):
  File "D:/hlp/github/hlp/hlp/chat/execute.py", line 3, in <module>
    import model.Seq2Seq.seq2seq as seq2seq
  File "D:\hlp\github\hlp\hlp\chat\model\Seq2Seq\seq2seq.py", line 54, in <module>
    input_tensor, input_token, target_tensor, target_token = read_data(config['seq_data'], config['max_train_data_size'])
  File "D:\hlp\github\hlp\hlp\chat\model\Seq2Seq\seq2seq.py", line 37, in read_data
    input_lang, target_lang = create_dataset(path, num_examples)
  File "D:\hlp\github\hlp\hlp\chat\model\Seq2Seq\seq2seq.py", line 27, in create_dataset
    lines = io.open(path, encoding='UTF-8').read().strip().split('\n')
FileNotFoundError: [Errno 2] No such file or directory: 'data/seq.data'

数据加载代码所在位置不对，需要重构。

**Comment by DengBoCong** [comment]
位置是没问题的，是data目录下的数据集我没有传上去，因为比较大不好传。关于数据集我下一个issue准备放在服务器上，然后用API进行读取。

**Comment by hlp-ai** [comment]
> 位置是没问题的，是data目录下的数据集我没有传上去，因为比较大不好传，我在.gitignore里忽略了data目录上传。关于数据集我下一个issue准备放在服务器上，然后用API进行读取。

只需要保证程序运行的最小数据集即可。
训练数据放到服务器上吗？这个不行。

**Comment by hlp-ai** [comment]
配置文件用一种格式的即可。不要ini、json和xml都有。不倾向使用xml。

**Comment by hlp-ai** [comment]
注释是一种习惯，可以逐步完善。最好是方法的功能要在提交时就有描述，其他可以逐步补充。

**Comment by hlp-ai** [comment]
训练程序最好单独分开。
