### ISSUE TITLE
熟悉Tacotron2模型

### ISSUE THREAD

**Issue by angletxm** [hlp-ai/hlp#3]
1.对比Tacotron2与Tacotron 的区别，了解Tacotron2模型的具体每一步如何实现
2.配置Tacotron2的模型的训练环境
3.研读并复现GitHub项目https://github.com/Rookie-Chenfy/Tacotron-2

**Comment by hlp-ai** [comment]
此Issue可以作为讨论记录使用。作为任务有点大。

**Comment by hlp-ai** [comment]
和马潇潇分个工，一个Tactoron，一个WaveNet。
